@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.opensiege.go;

import lofimodding.opensiege.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
