@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.opensiege.formats.aspect;

import lofimodding.opensiege.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
